name: Verificación de Código en Múltiples Lenguajes

on:
  push:
    branches:
      - main

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Installation Directory
        run: mkdir -p ~/instalaciones

      - name: Install .NET Core
        run: |
          if [ ! -f ~/instalaciones/dotnet/dotnet ]; then
            echo "Installing .NET Core..."
            wget -O dotnet-sdk.tar.gz https://download.visualstudio.microsoft.com/download/pr/60218cc4-13eb-41d5-aa0b-5fd5a3fb03b8/6c42bee7c3651b1317b709a27a741362/dotnet-sdk-8.0.303-linux-x64.tar.gz
            if [ $? -ne 0 ]; then
              echo "Failed to download .NET SDK"
              exit 1
            fi
            mkdir -p ~/instalaciones/dotnet
            tar -xzvf dotnet-sdk.tar.gz -C ~/instalaciones/dotnet
            if [ ! -f ~/instalaciones/dotnet/dotnet ]; then
              echo "Creating symbolic link for .NET Core..."
              ln -s ~/instalaciones/dotnet/dotnet ~/instalaciones/dotnet/dotnet
            else
              echo ".NET Core is already installed."
            fi
          else
            echo ".NET Core is already installed."
          fi

      - name: Install Python
        run: |
          if [ ! -f ~/instalaciones/python/python ]; then
            echo "Installing Python..."
            sudo apt-get update
            sudo apt-get install -y python3 python3-pip
            mkdir -p ~/instalaciones/python
            ln -s /usr/bin/python3 ~/instalaciones/python/python
            ln -s /usr/bin/pip3 ~/instalaciones/python/pip
          else
            echo "Python is already installed."
          fi

      - name: Install Ruby
        run: |
          if [ ! -f ~/instalaciones/ruby/ruby ]; then
            echo "Installing Ruby..."
            sudo apt-get install -y ruby
            mkdir -p ~/instalaciones/ruby
            ln -s /usr/bin/ruby ~/instalaciones/ruby/ruby
            ln -s /usr/bin/gem ~/instalaciones/ruby/gem
          else
            echo "Ruby is already installed."
          fi

      - name: Install Lua
        run: |
          if [ ! -f ~/instalaciones/lua/lua ]; then
            echo "Installing Lua..."
            sudo apt-get install -y lua5.3
            mkdir -p ~/instalaciones/lua
            ln -s /usr/bin/lua5.3 ~/instalaciones/lua/lua
          else
            echo "Lua is already installed."
          fi

      - name: Install C/C++ Compiler
        run: |
          if [ ! -f ~/instalaciones/cpp/gcc ]; then
            echo "Installing C/C++ Compiler..."
            sudo apt-get install -y build-essential
            mkdir -p ~/instalaciones/cpp
            ln -s /usr/bin/gcc ~/instalaciones/cpp/gcc
            ln -s /usr/bin/g++ ~/instalaciones/cpp/g++
          else
            echo "C/C++ Compiler is already installed."
          fi

      - name: Run Python Tests
        run: |
          export PATH=~/instalaciones/python:$PATH
          mkdir -p logs
          for file in $(find . -name "*.py"); do
            echo "Running $file"
            python "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run Ruby Tests
        run: |
          export PATH=~/instalaciones/ruby:$PATH
          mkdir -p logs
          for file in $(find . -name "*.rb"); do
            echo "Running $file"
            ruby "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run C# Tests
        run: |
          export PATH=~/instalaciones/dotnet:$PATH
          mkdir -p logs
          for file in $(find . -name "*.csproj"); do
            echo "Building $file"
            dotnet build "$file" > "logs/$(basename "$file").build.log" 2>&1 || echo "$file build failed. Check logs/$(basename "$file").build.log for details."
            echo "Running $file"
            dotnet run --project "$file" > "logs/$(basename "$file").run.log" 2>&1 || echo "$file run failed. Check logs/$(basename "$file").run.log for details."
          done

      - name: Run Lua Tests
        run: |
          export PATH=~/instalaciones/lua:$PATH
          mkdir -p logs
          for file in $(find . -name "*.lua"); do
            echo "Running $file"
            lua "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run C++ Tests
        run: |
          export PATH=~/instalaciones/cpp:$PATH
          mkdir -p logs
          for file in $(find . -name "*.cpp"); do
            echo "Compiling $file"
            g++ -o "build/$(basename "${file%.cpp}.out")" "$file" > "logs/$(basename "$file").compile.log" 2>&1 || echo "$file compile failed. Check logs/$(basename "$file").compile.log for details."
            echo "Running build/$(basename "${file%.cpp}.out")"
            "./build/$(basename "${file%.cpp}.out")" > "logs/$(basename "${file%.cpp}.out").run.log" 2>&1 || echo "Execution of $(basename "${file%.cpp}.out") failed. Check logs/$(basename "${file%.cpp}.out").run.log for details."
          done

      - name: Run C Tests
        run: |
          export PATH=~/instalaciones/cpp:$PATH
          mkdir -p logs
          for file in $(find . -name "*.c"); do
            echo "Compiling $file"
            gcc -o "build/$(basename "${file%.c}.out")" "$file" > "logs/$(basename "$file").compile.log" 2>&1 || echo "$file compile failed. Check logs/$(basename "$file").compile.log for details."
            echo "Running build/$(basename "${file%.c}.out")"
            "./build/$(basename "${file%.c}.out")" > "logs/$(basename "${file%.c}.out").run.log" 2>&1 || echo "Execution of $(basename "${file%.c}.out") failed. Check logs/$(basename "${file%.c}.out").run.log for details."
          done

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: Error en el repositorio
          to: davikenat@gmail.com
          body: |
            Error encontrado en el repositorio.
            Detalles del error:
            - Repositorio: ${{ github.repository }}
            - Rama: ${{ github.ref }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Revisa los logs del workflow en el directorio `logs` para más detalles.
