name: Verificación de Código en Múltiples Lenguajes

on:
  push:
    branches:
      - main  # Cambia esto a la rama principal de tu repositorio

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Install Lua
        run: sudo apt-get install -y lua5.3

      - name: Setup C/C++ Compiler
        run: sudo apt-get install -y build-essential

      - name: Run Python Tests
        run: |
          for file in $(find . -name "*.py"); do
            echo "Running $file"
            python "$file"
          done

      - name: Run Ruby Tests
        run: |
          for file in $(find . -name "*.rb"); do
            echo "Running $file"
            ruby "$file"
          done

      - name: Run C# Tests
        run: |
          for file in $(find . -name "*.csproj"); do
            echo "Building $file"
            dotnet build "$file"
            echo "Running $file"
            dotnet run --project "$file"
          done

      - name: Run Lua Tests
        run: |
          for file in $(find . -name "*.lua"); do
            echo "Running $file"
            lua "$file"
          done

      - name: Run C++ Tests
        run: |
          for file in $(find . -name "*.cpp"); do
            echo "Compiling $file"
            g++ -o "${file%.cpp}.out" "$file"
            echo "Running ${file%.cpp}.out"
            "./${file%.cpp}.out"
          done

      - name: Run C Tests
        run: |
          for file in $(find . -name "*.c"); do
            echo "Compiling $file"
            gcc -o "${file%.c}.out" "$file"
            echo "Running ${file%.c}.out"
            "./${file%.c}.out"
          done

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}  # Configura el remitente del correo
          subject: Error en el repositorio
          to: davikenat@gmail.com
          body: |
            Error encontrado en el repositorio.
            Detalles del error:
            - Repositorio: ${{ github.repository }}
            - Rama: ${{ github.ref }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Revisa los logs del workflow para más detalles.

      - name: Log debug information
        if: failure()
        run: |
          echo "Mostrando registros de flujo de trabajo para depuración..."
          cat $GITHUB_ENV
