name: Verificación de Código

on:
  push:
    branches:
      - main

jobs:
  test-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '5.0.x'

      - name: Install Lua
        run: sudo apt-get install -y lua5.3

      - name: Setup C/C++ Compiler
        run: sudo apt-get install -y build-essential

      - name: Run Python Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.py"); do
            echo "Running $file"
            python "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run Ruby Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.rb"); do
            echo "Running $file"
            ruby "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run C# Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.csproj"); do
            echo "Building $file"
            dotnet build "$file" > "logs/$(basename "$file").build.log" 2>&1 || echo "$file build failed. Check logs/$(basename "$file").build.log for details."
            echo "Running $file"
            dotnet run --project "$file" > "logs/$(basename "$file").run.log" 2>&1 || echo "$file run failed. Check logs/$(basename "$file").run.log for details."
          done

      - name: Run Lua Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.lua"); do
            echo "Running $file"
            lua "$file" > "logs/$(basename "$file").log" 2>&1 || echo "$file failed. Check logs/$(basename "$file").log for details."
          done

      - name: Run C++ Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.cpp"); do
            echo "Compiling $file"
            g++ -o "build/$(basename "${file%.cpp}.out")" "$file" > "logs/$(basename "$file").compile.log" 2>&1 || echo "$file compile failed. Check logs/$(basename "$file").compile.log for details."
            echo "Running build/$(basename "${file%.cpp}.out")"
            "./build/$(basename "${file%.cpp}.out")" > "logs/$(basename "${file%.cpp}.out").run.log" 2>&1 || echo "Execution of $(basename "${file%.cpp}.out") failed. Check logs/$(basename "${file%.cpp}.out").run.log for details."
          done

      - name: Run C Tests
        run: |
          mkdir -p logs
          for file in $(find . -name "*.c"); do
            echo "Compiling $file"
            gcc -o "build/$(basename "${file%.c}.out")" "$file" > "logs/$(basename "$file").compile.log" 2>&1 || echo "$file compile failed. Check logs/$(basename "$file").compile.log for details."
            echo "Running build/$(basename "${file%.c}.out")"
            "./build/$(basename "${file%.c}.out")" > "logs/$(basename "${file%.c}.out").run.log" 2>&1 || echo "Execution of $(basename "${file%.c}.out") failed. Check logs/$(basename "${file%.c}.out").run.log for details."
          done

      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.GMAIL_USERNAME }}
          password: ${{ secrets.GMAIL_PASSWORD }}
          from: ${{ secrets.GMAIL_USERNAME }}
          subject: Error en el repositorio
          to: ikisantmar@gmail.com
          body: |
            Error encontrado en el repositorio.
            Detalles del error:
            - Repositorio: ${{ github.repository }}
            - Rama: ${{ github.ref }}
            - Workflow: ${{ github.workflow }}
            - Run ID: ${{ github.run_id }}
            - Revisa los logs del workflow en el directorio `logs` para más detalles.
