- name: Send test email
  uses: dawidd6/action-send-mail@v3
  with:
    server_address: smtp.gmail.com
    server_port: 587
    username: ${{ secrets.GMAIL_USERNAME }}
    password: ${{ secrets.GMAIL_PASSWORD }}
    from: ${{ secrets.GMAIL_USERNAME }}
    to: davikenat@gmail.com
    subject: Test Email
    body: Este es un correo de prueba para verificar la configuración del servidor de correo.
